[package]
name = "docopt"
version = "0.7.0"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Command line argument parsing."
documentation = "http://burntsushi.net/rustdoc/docopt/"
homepage = "https://github.com/docopt/docopt.rs"
repository = "https://github.com/docopt/docopt.rs"
readme = "README.md"
keywords = ["docopt", "argument", "command", "argv"]
license = "Unlicense/MIT"

[lib]
name = "docopt"

[[bin]]
name = "docopt-wordlist"
path = "src/wordlist.rs"
doc = false
test = false

[dependencies]
lazy_static = "0.2"
regex = "0.2"
rustc-serialize = "0.3"
strsim = "0.6"
